// Mod Mirror — pure renderer for the public, aggregate-only case-law page.
// No usernames, no permalinks, no item bodies. Counts and rates only.
import type { ReceiptRecord } from './types.ts';
import { computeRuleStats } from './caseLaw.ts';

const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;

export interface MirrorRuleRow {
  label: string;
  slug: string;
  total: number;
  overturned: number;
  upheld: number;
  appealed: number;
  reversalRatePct: number;
  last30Days: number;
  mostRecentTs: number;
}

/** Pure transform: take the per-rule receipt records and produce one row per rule. */
export function rollupRule(input: {
  label: string;
  slug: string;
  records: ReceiptRecord[];
  now: number;
}): MirrorRuleRow {
  const stats = computeRuleStats(input.records);
  const reversalRatePct = stats.total > 0 ? Math.round((stats.overturned / stats.total) * 100) : 0;
  const cutoff = input.now - THIRTY_DAYS_MS;
  const last30Days = input.records.filter((r) => r.ts >= cutoff).length;
  const mostRecentTs = input.records.reduce((m, r) => (r.ts > m ? r.ts : m), 0);
  return {
    label: input.label,
    slug: input.slug,
    total: stats.total,
    overturned: stats.overturned,
    upheld: stats.upheld,
    appealed: stats.appealed,
    reversalRatePct,
    last30Days,
    mostRecentTs,
  };
}

// Public-wiki cell sanitizer: escape characters that would break a markdown table
// row or render arbitrary formatting/links on the public page.
function escapeMd(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/\|/g, '\\|')
    .replace(/`/g, '\\`')
    .replace(/\[/g, '\\[')
    .replace(/\]/g, '\\]')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\r?\n/g, ' ');
}

/** Public-mirror rule-label sanitizer. The rule label is derived from mod free-text
 *  removal reasons, which can contain Reddit usernames ("removed u/bob's spam ring") or
 *  URLs (attacker-supplied). Strip both before the label can land on the public wiki. */
export function sanitizeRuleLabel(input: string): string {
  if (!input) return '';
  return input
    .replace(/\bu\/[A-Za-z0-9_-]+/g, 'u/[redacted]')
    .replace(/\/u\/[A-Za-z0-9_-]+/g, '/u/[redacted]')
    .replace(/https?:\/\/\S+/gi, '[link]')
    .replace(/\s+/g, ' ')
    .trim();
}

function fmtDate(ts: number): string {
  return ts > 0 ? new Date(ts).toISOString().slice(0, 10) : '—';
}

/** Render the full Mirror markdown for a subreddit. Rules are sorted by total desc. */
export function renderMirrorMarkdown(input: {
  subreddit: string;
  rules: MirrorRuleRow[];
  generatedAt: number;
}): string {
  const lines: string[] = [];
  lines.push(`# Anvil Court — moderation case law for r/${input.subreddit}`);
  lines.push('');
  lines.push(`*Last updated: ${new Date(input.generatedAt).toISOString().slice(0, 19).replace('T', ' ')} UTC*`);
  lines.push('');
  lines.push(
    `Aggregated, anonymized public record of moderation decisions in r/${input.subreddit}, ` +
      `automatically generated by [Anvil Court](https://github.com/Alexander-Sorrell-IT/anvilcourt-devvit). ` +
      `Counts are lifetime since installation; reversal rate is overturned ÷ total.`,
  );
  lines.push('');
  lines.push(
    `*This page intentionally publishes no usernames, no item bodies, and no permalinks ` +
      `— only counts. To see your own removal history, DM r/${input.subreddit} with **/my-receipts**.*`,
  );
  lines.push('');

  if (input.rules.length === 0) {
    lines.push('_No moderation decisions have been logged yet._');
    return lines.join('\n');
  }

  const sorted = [...input.rules].sort((a, b) => b.total - a.total).slice(0, 50);
  const totals = sorted.reduce(
    (acc, r) => ({
      total: acc.total + r.total,
      overturned: acc.overturned + r.overturned,
      appealed: acc.appealed + r.appealed,
      last30: acc.last30 + r.last30Days,
    }),
    { total: 0, overturned: 0, appealed: 0, last30: 0 },
  );
  const overallRate = totals.total > 0 ? Math.round((totals.overturned / totals.total) * 100) : 0;

  lines.push('## Summary');
  lines.push('');
  lines.push(
    `**${totals.total}** total decisions, **${totals.overturned} overturned** (${overallRate}%), ` +
      `**${totals.appealed} open appeal(s)**, **${totals.last30}** in the last 30 days.`,
  );
  lines.push('');
  lines.push('## Per-rule breakdown');
  lines.push('');
  lines.push('| Rule | Total | Overturned | Reversal rate | Last 30 days | Most recent |');
  lines.push('|---|---:|---:|---:|---:|---:|');
  for (const r of sorted) {
    lines.push(
      `| ${escapeMd(r.label)} | ${r.total} | ${r.overturned} | ${r.reversalRatePct}% | ${r.last30Days} | ${fmtDate(r.mostRecentTs)} |`,
    );
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(
    '_Generated by the Anvil Court mod tool. ' +
      'Anvil Court records moderation decisions (mod removals, AutoMod silent filters, AutoMod removals; ' +
      'Reddit spam-filter coverage is opt-in) ' +
      'and turns the audit log into queryable precedent. ' +
      'When a user appeals, the rule\'s prior outcomes auto-render for the mod team. ' +
      'A mod can reverse the removal with one reply — the decision is logged here too._',
  );
  return lines.join('\n');
}
